<?php

function website_cart_mail($key, &$message, $params) {
    $options = array(
        'langcode' => $message['langcode'],
      );
     
    switch ($key) {
      case 'submit_order':
        $message['from'] = 'info@houstonsnaturalmeats.com';
        $message['reply-to'] = $message['from'];
        $message['subject'] = 'New Order Received';
        $message['body'][] = $params['message'];
	$message['headers'] = [
		'Bcc' => $message['from'],
	];
        break;
    }

}
